spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tutorial?useSSL=false&allowPublicKeyRetrieval=true
    username: tutorial
    password: tutorial123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

